[package]
name = "async-functions"
version = "0.1.0"
authors = ["onurakkaya"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-recursion = "0.3.1"